FROM almalinux
# RUN cd  /tmp
# RUN PWD
RUN mkdir /app
WORKDIR /app
RUN PWD
CMD ["sleep", "infinity"] # This command keeps the container running indefinitely, allowing us to inspect the working directory when we run the container. 