FROM almalinux:9
ADD https://raw.githubusercontent.com/daws-86s/notes/refs/heads/main/session-01.txt /tmp/notes.txt
CMD [sleep", "infinity"] # This command keeps the container running indefinitely, allowing us to inspect the added file when we run the container.