FROM almalinux:9
ENV COURSE="docker" \
    TRAINER="shiva" \
    DURATION="2hrs"

CMD [sleep", "infinity"] # This command keeps the container running indefinitely, allowing us to inspect the environment variables when we run the container.